# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cliente\Documents\Eu\cadastro_evento_atualizado.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 624)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"QMenuBar::hover {\n"
"    background-color: black;\n"
"    color: black;\n"
"}\n"
"\n"
"\n"
"QMenuBar#QMenuBar:hover {\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(40, 0, 941, 491))
        self.widget.setMouseTracking(True)
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("\n"
"\n"
"QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(236, 141, 26, 219), stop: 1 rgba(160, 96, 18, 180));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"background-color: rgba(0,0,0,0);\n"
"color: rgba(85,98,112,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_2:hover,#pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover {\n"
"color: rgba(131,96,53,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"padding-left: 5px;\n"
"padding-top:5px;\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(0, 71, 135, 219), stop: 1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(150, 123, 111, 255)\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(540, 40, 621, 430))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255,255);\n"
"border-bottom-right-radius:50px;\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("G:\Meu Drive\Projeto Integrador\Python\PI_Atualização\Img\image_evento.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(90, 30, 411, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(0, 0, 0, 150)")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 100, 311, 40))
        self.lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 160, 311, 51))
        self.lineEdit_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 420, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #000000, stop: 0.5 #808080, stop: 1 #FFFFFF);\n"
"color: black;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 420, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #000000, stop: 0.5 #808080, stop: 1 #FFFFFF);\n"
"color: black;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 230, 311, 61))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(120, 280, 311, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 310, 311, 61))
        self.lineEdit_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(120, 360, 311, 22))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionCadastrar_usu_rio = QtWidgets.QAction(MainWindow)
        self.actionCadastrar_usu_rio.setObjectName("actionCadastrar_usu_rio")
        self.actionEditar_Deletar = QtWidgets.QAction(MainWindow)
        self.actionEditar_Deletar.setObjectName("actionEditar_Deletar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionConsulta_cadastros = QtWidgets.QAction(MainWindow)
        self.actionConsulta_cadastros.setObjectName("actionConsulta_cadastros")
        self.actionConsulta_faltas = QtWidgets.QAction(MainWindow)
        self.actionConsulta_faltas.setObjectName("actionConsulta_faltas")
        self.actionCadastrar_aula = QtWidgets.QAction(MainWindow)
        self.actionCadastrar_aula.setObjectName("actionCadastrar_aula")
        self.actionCadastrar_mat_ria = QtWidgets.QAction(MainWindow)
        self.actionCadastrar_mat_ria.setObjectName("actionCadastrar_mat_ria")
        self.actionMat_ria = QtWidgets.QAction(MainWindow)
        self.actionMat_ria.setObjectName("actionMat_ria")
        self.actionCurso = QtWidgets.QAction(MainWindow)
        self.actionCurso.setObjectName("actionCurso")
        self.actionAula = QtWidgets.QAction(MainWindow)
        self.actionAula.setObjectName("actionAula")
        self.actionUsu_rio = QtWidgets.QAction(MainWindow)
        self.actionUsu_rio.setObjectName("actionUsu_rio")
        self.actionO_que_PIN = QtWidgets.QAction(MainWindow)
        self.actionO_que_PIN.setObjectName("actionO_que_PIN")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "CADASTRO DE EVENTOS"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nome do evento"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Descrição do evento"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_3.setText(_translate("MainWindow", "Cadastrar"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Data e hora do ínicio do evento"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Data e hora do término do evento"))
        self.actionCadastrar_usu_rio.setText(_translate("MainWindow", "Cadastrar usuário"))
        self.actionEditar_Deletar.setText(_translate("MainWindow", "Editar / Deletar"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionConsulta_cadastros.setText(_translate("MainWindow", "Consulta cadastros"))
        self.actionConsulta_faltas.setText(_translate("MainWindow", "Consulta faltas"))
        self.actionCadastrar_aula.setText(_translate("MainWindow", "Cadastrar aula"))
        self.actionCadastrar_mat_ria.setText(_translate("MainWindow", "Cadastrar matéria"))
        self.actionMat_ria.setText(_translate("MainWindow", "Matéria"))
        self.actionCurso.setText(_translate("MainWindow", "Curso"))
        self.actionAula.setText(_translate("MainWindow", "Aula"))
        self.actionUsu_rio.setText(_translate("MainWindow", "Usuário"))
        self.actionO_que_PIN.setText(_translate("MainWindow", "O que é PIN?"))
